In [1]:
import numpy as np
    
from sklearn.datasets import load_iris
dataset = load_iris()

	

In [30]:
print(type(dataset))
print(dataset.keys())
print(dataset.data[:10])
print(f'targets are {dataset.target[:10]}')
print(f'targets names are {dataset.target_names[:10]}')

means = np.mean(dataset.data, axis=0)
medians=np.median(dataset.data, axis=0)
stds=np.std(dataset.data, axis=0)

print(f'mean is = {means}')
print(f'median is = {medians}')
print(f'std is = {stds}')


<class 'sklearn.utils._bunch.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
targets are [0 0 0 0 0 0 0 0 0 0]
targets names are ['setosa' 'versicolor' 'virginica']
mean is = [5.84333333 3.05733333 3.758      1.19933333]
median is = [5.8  3.   4.35 1.3 ]
std is = [0.82530129 0.43441097 1.75940407 0.75969263]


In [28]:
Dataset_X = {2, 2, 2, 3, 4, 8, 3, 4, 2, 5, 9, 3}
ls_dataset=list(Dataset_X)
print(np.median(ls_dataset))

4.5


In [ ]:
import pandas as pd
dataset = pd.read_csv('mushrooms.csv')
# Write your code here. Do not change any other parts of the code
print(poisonous_percentage)
return edible_count, edible_percentage, cap_colors	