In [1]:
# RNN
from tensorflow import keras
import numpy as np

from tensorflow.keras.datasets import imdb

(x_train, y_train), (x_test, y_test) = imdb.load_data(
    path="imdb.npz",
    num_words=None,
    skip_top=0,
    maxlen=None,
    seed=113,
    start_char=1,
    oov_char=2,
    index_from=3,
)
#only include the first 1000 data
x_train=x_train[0:120]
y_train=y_train[0:120]
x_test=x_test[0:100]
y_test=y_test[0:100]




In [2]:
x_train=np.array(x_train)
print ("size of x_train",x_train.shape)
print("type of x_train", type(x_train))
print("x_train[0]",x_train[0:2])
print("y_train[0]",y_train[0])

size of x_train (120,)
type of x_train <class 'numpy.ndarray'>
x_train[0] [list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 447

In [6]:
# Retrieve the word index file mapping words to indices
tokens = keras.datasets.imdb.get_word_index()

#get the size of tokens
len(tokens)

88584

In [7]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

#Use a loop to find the longest subsequence in the dataset
sequence_length = max([len(sequence) for sequence in x_train])
sequence_length =max(sequence_length,50)
# Pad all the subsequences with 0's, and add to the front of the data
sequences = pad_sequences(x_train, maxlen=sequence_length, padding='post')

# Print the shape of the padded sequences
print(sequences.shape)


(120, 1038)


In [7]:
subsequences = []
for sequence in x_train:
    for i in range(1, len(sequence)):
        subsequence = sequence[:i+1]
        subsequences.append(subsequence)
#visualize the new set-up
print(subsequences[1:10])
print(sequences.size)

[[1, 14, 22], [1, 14, 22, 16], [1, 14, 22, 16, 43], [1, 14, 22, 16, 43, 530], [1, 14, 22, 16, 43, 530, 973], [1, 14, 22, 16, 43, 530, 973, 1622], [1, 14, 22, 16, 43, 530, 973, 1622, 1385], [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65], [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458]]
124560


## Add a padding layer around the sequences to standardize the length of our training phrases. 

In [8]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

#Use a loop to find the longest subsequence in the dataset
sequence_length = max([len(sequence) for sequence in sequences])

# Pad all the sequences with 0's, and add to the front of the data
padded_sequences = pad_sequences(sequences, maxlen=sequence_length, padding='post')

# Print the shape of the padded sequences
print("shoape of padded_sequences=",padded_sequences.shape)
#print a sample of sequences
print(padded_sequences[1])
#limit the sequence length to 150
limitedsize = min(sequence_length, 150)
padded_sequences_limitedsize=padded_sequences[:,0:limitedsize]
print("size of padded_sequences_limitedsize=",padded_sequences_limitedsize.shape)
print("size of y-train=", y_train.shape)

shoape of padded_sequences= (120, 1038)
[   1  194 1153 ...    0    0    0]
size of padded_sequences_limitedsize= (120, 150)
size of y-train= (120,)


In [10]:
#train a ANN to preidct y_train from sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout, Dense
x_train_encoded=padded_sequences_limitedsize
model = Sequential()
model.add(Dense(units = x_train_encoded.shape[1], activation = 'relu', input_dim = x_train_encoded.shape[1]))
model.add(Dropout(rate = 0.1))
model.add(Dense(units = 50, activation = 'relu'))
model.add(Dropout(rate = 0.1))
model.add(Dense(units = 1, activation = 'sigmoid'))
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.fit(x_train_encoded, y_train, epochs = 10, batch_size = 32)

#predict y_test from sequences

: 

In [ ]:
print(x_train_encoded[0:18])
print("sequences shape=",x_train_encoded.shape)
print("shape=",y_train.shape)

[[   1   14   22 ...   71   43  530]
 [   1  194 1153 ... 9837  131  152]
 [   1   14   47 ...    0    0    0]
 ...
 [   1    6  964 ...    0    0    0]
 [   1 7092 1662 ...   40 7302  808]
 [   1   33    4 ...  100   28  256]]
sequences shape= (200, 150)
shape= (200,)


In [34]:
#test the model on a data from x_test
x_test=x_test[0:100]
padded_sequences_test = pad_sequences(x_test, maxlen=sequence_length, padding='post')
padded_sequences_test_limitedsize=padded_sequences_test[:,0:limitedsize]
print("size of padded x_text sequences=",padded_sequences_test_limitedsize.shape)




size of padded x_text sequences= (100, 150)


In [ ]:
# evaluate the accuracy of th model


### 5. Split the lines of words into input and output.  

The last word of each line is now the fartherst right word on each line because of all the padding zeros pushing it over the appropriate number of spots. You can grab the output (our 'label') now, because the next word in the line is always in the last column. No I can easily see what collection of words goes before any given word. Cool!

In [36]:
x, y = sequences[:,:-1],sequences[:,-1]
print(y)
print(np.unique(y))
print(len(np.unique(y)))

[  14   22   16 ... 2450 5486 3298]
[    4     5     6 ... 88210 88377 88552]
5459


### Step 6: Pivot the output column into columns (dummy columns of either 0 or 1)

In [37]:
from keras.utils import to_categorical
vocabulary_size = len(tokens) + 1
vocabulary_size
y = to_categorical(y, num_classes=vocabulary_size) # num_classes does (value - 1) columns

In [38]:
y.shape

(26947, 88585)

## 7. Create the RNN to predict the next word

Define an RNN with the following layers:

An embedding layer with the following parameters:
<br> The input dimension is vocabulary_size
<br> The output dimension is 100
<br> The input length is sequence_length - 1
<br> An LSTM layer with 100 units
<br> A dropout layer with a dropout rate of 10%
<br> A dense layer with the following parameters:
<br> The activation function is softmax
<br> The number of units is vocabulary_size

In [ ]:
from keras.models import Sequential 
from keras.layers import LSTM 
from keras.layers import Embedding

model = Sequential()
model.add(Embedding(input_dim = vocabulary_size, 
                    output_dim = 100,
                    input_shape = (sequence_length - 1,)))


model.add(LSTM(units = 10))
from keras.layers import Dropout, Dense 
model.add(Dropout(rate=0.1))
model.add(Dense(units=vocabulary_size, activation ='softmax'))
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 887, 100)       │     8,858,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 10)             │         4,440 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 10)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 88585)          │       974,435 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,837,375 (37.53 MB)

 Trainable params: 9,837,375 (37.53 MB)

 Non-trainable params: 0 (0.00 B)